// Generated by GitHub Copilot
console.log("PAYMENT ROUTE FILE LOADED");
const express = require("express");
const Razorpay = require("razorpay");

const router = express.Router();

/**
 * Lazily initialise Razorpay only when keys are provided.
 * This allows the server to start without payment credentials (e.g. local dev).
 */
function getRazorpay() {
  if (!process.env.RAZORPAY_KEY_ID || !process.env.RAZORPAY_KEY_SECRET) {
    throw new Error("Razorpay keys are not configured. Set RAZORPAY_KEY_ID and RAZORPAY_KEY_SECRET.");
  }
  return new Razorpay({
    key_id: process.env.RAZORPAY_KEY_ID,
    key_secret: process.env.RAZORPAY_KEY_SECRET,
  });
}

router.post("/create-order", async (req, res) => {

    console.log("PAYMENT API HIT");

  try {
    const razorpay = getRazorpay();
    const order = await razorpay.orders.create({
      amount: 50000,
      currency: "INR",
      receipt: "fee_receipt"
    });

    res.json(order);
  } catch (error) {
    console.log(error);
    res.status(500).send("Payment Error");
  }
});

module.exports = router;