// Generated by GitHub Copilot
import axios from "axios";

const API_BASE = import.meta.env.VITE_API_URL || "https://smart-campus-management-asv4.onrender.com";

function Fees() {

  const totalFees = 50000;
  const paidFees = 35000;
  const pendingFees = totalFees - paidFees;

 
 const handlePayment = async () => {

  try {

    const response = await axios.post(`${API_BASE}/payment/create-order`);

    console.log(response.data);

    const order = response.data;

    const options = {
      // Public key — safe to expose in the browser; secret stays server-side
      key: import.meta.env.VITE_RAZORPAY_KEY_ID,
      amount: order.amount,
      currency: order.currency,
      name: "Smart Campus",
      description: "Fee Payment",
      order_id: order.id,

      handler: function () {
        alert("Payment Successful");
      }
    };

    const razorpay = new window.Razorpay(options);

    razorpay.open();

  }

  catch(error){

    console.log(error);
    alert("Payment failed. Please try again.");

  }

};

  return (

    <div style={{padding:"30px"}}>

      <h1>Fee Payment Module</h1>

      <div style={{
        display:"flex",
        gap:"20px",
        marginTop:"20px"
      }}>

        <div style={cardStyle}>
          <h2>Total Fees</h2>
          <p>₹ {totalFees}</p>
        </div>

        <div style={cardStyle}>
          <h2>Paid Fees</h2>
          <p>₹ {paidFees}</p>
        </div>

        <div style={cardStyle}>
          <h2>Pending Fees</h2>
          <p>₹ {pendingFees}</p>
        </div>

      </div>

      <h2 style={{marginTop:"40px"}}>
        Payment History
      </h2>

      <table
        border="1"
        cellPadding="10"
        style={{
          width:"100%",
          marginTop:"20px",
          borderCollapse:"collapse", 
          backgroundColor:"white",
          color:"black"
        }}
      >

        <thead>

          <tr>
            <th>Date</th>
            <th>Amount</th>
            <th>Status</th>
          </tr>

        </thead>

        <tbody>

          <tr>
            <td>10-01-2026</td>
            <td>₹ 20000</td>
            <td>Paid</td>
          </tr>

          <tr>
            <td>15-03-2026</td>
            <td>₹ 15000</td>
            <td>Paid</td>
          </tr>

        </tbody>

      </table>

      <button
        style={{
          marginTop:"30px",
          padding:"12px 20px",
          backgroundColor:"green",
          color:"white",
          border:"none",
          borderRadius:"8px",
          cursor:"pointer"
        }}

        onClick={handlePayment}
      >

        Pay Fees

      </button>

    </div>

  );

}

const cardStyle = {
  backgroundColor:"white",
  padding:"20px",
  borderRadius:"10px",
  boxShadow:"0 0 10px rgba(0,0,0,0.1)",
  width:"200px"
};

export default Fees;