// Generated by GitHub Copilot
import { useState } from "react";
import axios from "axios";
import { useNavigate } from "react-router-dom";

const API_BASE = import.meta.env.VITE_API_URL || "https://smart-campus-management-asv4.onrender.com";

function Login() {

  const navigate = useNavigate();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [role, setRole] = useState("Student");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handleLogin = async () => {

    setError("");

    if (!email.trim() || !password.trim()) {
      setError("Email and password are required.");
      return;
    }

    setLoading(true);

    try {
      const res = await axios.post(`${API_BASE}/login`, {
        email: email.trim(),
        password,
        role,
      });

      // res.data is { success: true, message: "Login Success", user: {...} }
      if (res.data.success) {
        if (role === "Student") {
          navigate("/student");
        } else if (role === "Faculty") {
          navigate("/faculty");
        } else {
          navigate("/admin");
        }
      }
    } catch (err) {
      console.log(err);
      const msg = err.response?.data?.message || "Login failed. Check your credentials.";
      setError(msg);
    } finally {
      setLoading(false);
    }

  };

 return (
  <div className="container">

    <div className="card">

      <h1>Smart Campus Management Platform</h1>

      {error && (
        <p role="alert" style={{ color: "red", marginBottom: "10px" }}>
          {error}
        </p>
      )}

      <input
        type="email"
        placeholder="Enter Email"
        aria-label="Email address"
        onChange={(e) => setEmail(e.target.value)}
      />

      <input
        type="password"
        placeholder="Enter Password"
        aria-label="Password"
        onChange={(e) => setPassword(e.target.value)}
      />

      <select
        aria-label="Select role"
        onChange={(e) => setRole(e.target.value)}
      >
        <option>Student</option>
        <option>Faculty</option>
        <option>Admin</option>
      </select>

      <button onClick={handleLogin} disabled={loading}>
        {loading ? "Logging in..." : "Login"}
      </button>

      <p>
        New user? <a href="/register">Register</a>
      </p>

    </div>

  </div>
);
   
}

export default Login;