// Generated by GitHub Copilot
import { useState } from "react";
import axios from "axios";

const API_BASE = import.meta.env.VITE_API_URL || "https://smart-campus-management-asv4.onrender.com";

function Register() {

  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [role, setRole] = useState("Student");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handleRegister = async () => {

    setError("");

    // Client-side validation before hitting the server
    if (!name.trim() || !email.trim() || !password.trim()) {
      setError("All fields are required.");
      return;
    }
    if (password.length < 6) {
      setError("Password must be at least 6 characters.");
      return;
    }

    setLoading(true);

    try {
      const res = await axios.post(`${API_BASE}/register`, {
        name: name.trim(),
        email: email.trim(),
        password,
        role,
      });

      // res.data is { success: true, message: "Registration successful" }
      alert(res.data.message);
      if (res.data.success) {
        window.location.href = "/";
      }
    } catch (err) {
      console.log("FULL ERROR:", err);
      const msg = err.response?.data?.message || "Registration failed. Please try again.";
      setError(msg);
    } finally {
      setLoading(false);
    }
  };


  return (
    <div className="container">
    <div className="card">

      <h1>Register</h1>

      {error && (
        <p role="alert" style={{ color: "red", marginBottom: "10px" }}>
          {error}
        </p>
      )}

      <input
        type="text"
        placeholder="Enter Name"
        aria-label="Full name"
        onChange={(e) => setName(e.target.value)}
      />

      <input
        type="email"
        placeholder="Enter Email"
        aria-label="Email address"
        onChange={(e) => setEmail(e.target.value)}
      />

      <input
        type="password"
        placeholder="Enter Password (min 6 characters)"
        aria-label="Password"
        onChange={(e) => setPassword(e.target.value)}
      />

      <select
        aria-label="Select role"
        onChange={(e) => setRole(e.target.value)}
      >
        <option>Student</option>
        <option>Faculty</option>
        <option>Admin</option>
      </select>

      <button onClick={handleRegister} disabled={loading}>
        {loading ? "Registering..." : "Register"}
      </button>

      <p>
        Already have an account? <a href="/">Login</a>
      </p>

    </div>
    </div>
  );
}

export default Register;